### PR TITLE
add chainbase nodes

### PR DESCRIPTION
**Pull request by f0rmatting**
Add chainbase nodes.

### CODE REVIEW

**Comment by arddluma** [comment]
Hey there! chainbase looks cool 💯 
Please take a look at my comments and will proceed with merging this !
Thank you :)

**Comment by f0rmatting** [comment]
Glad to hear that! We will support more chain soon!

**Comment by arddluma** [comment]
> Glad to hear that! We will support more chain soon!

Amazing stuff! Would like to discuss more about this. What's your discord acc?

**Comment by f0rmatting** [comment]
> Amazing stuff! Would like to discuss more about this. What's your discord acc?

formatting#4150

**Comment by f0rmatting** [comment]
Pls help merging this, thx

**Comment by arddluma** [comment]
Awesome 💯 Thanks for adding ChainBase to the list 🚀

**Pull request merged**
