### PR TITLE
feat: add chainnodes to list of providers

### PR DESCRIPTION
**Pull request by koraykoska**
Update from #143 

We support 6 networks now, though Goerli and Optimism-Goerli are not on your list. Also, we are around since January 2022.

### CODE REVIEW

**Comment by arddluma** [comment]
Hey,
Please resolve conflicts @koraykoska

**Comment by koraykoska** [comment]
@arddluma Resolved them!

**Comment by arddluma** [comment]
Merged 🎉 @koraykoska Happy to add Chainnodes to the list!

**Comment by koraykoska** [comment]
Thanks @arddluma 🎉

**Pull request merged**
