### PR TITLE
Added Blast as an API provider (https://blastapi.io)

### PR DESCRIPTION
**Pull request by eradus**

### CODE REVIEW

**Comment by arddluma** [comment]
Could you please resolve conflicts @eradus ?

**Comment by eradus** [comment]
> 

hey! sorry bout that! fixed!

**Comment by arddluma** [comment]
hey @eradus, sorry. Please remove everything else that is not needed.

**Comment by eradus** [comment]
> hey @eradus, sorry. Please remove everything else that is not needed.

hey! sorry again, forgot to hit save in the text editor 🙈 should be fine now

**Comment by arddluma** [comment]
> > hey @eradus, sorry. Please remove everything else that is not needed.
> 
> hey! sorry again, forgot to hit save in the text editor 🙈 should be fine now

hahahaha it happens all the time 🤣 
Could you pls on fantom section let PocketNetwork as nr5 and Blast API as 6. (sorry, we need to follow the order 🙏)
and letzz merge dis 🚀

**Comment by eradus** [comment]
> > > hey @eradus, sorry. Please remove everything else that is not needed.
> > 
> > 
> > hey! sorry again, forgot to hit save in the text editor 🙈 should be fine now
> 
> hahahaha it happens all the time 🤣 Could you pls on fantom section let PocketNetwork as nr5 and Blast API as 6. (sorry, we need to follow the order 🙏) and letzz merge dis 🚀

oh, sorry, it was added after my original PR, wasn't intentional :P, fixed!

**Comment by eradus** [comment]
> 

sure, no problem! may I ask the reason for that? 😁

**Comment by arddluma** [comment]
> sure, no problem! may I ask the reason for that? 😁

Yeah sure, the repo can be a bit longer if we add many entries there and we need to infinite scroll to the actual nodes.

**Comment by arddluma** [comment]
Thanks man! Hope you understand my point. Lezzz goo 💯🚀 I will merge this now!

**Comment by arddluma** [comment]
> > add
> 
> thanks ! 😁 It would be awesome for us if we could have a chat about the multichain section also but thanks for accepting our changes

Please tell me your twitter acc, we can chat there if you like 🙏

**Comment by eradus** [comment]
> > > add
> > 
> > 
> > thanks ! 😁 It would be awesome for us if we could have a chat about the multichain section also but thanks for accepting our changes
> 
> Please tell me your twitter acc, we can chat there if you like 🙏

Great! here it is: https://twitter.com/radu_enoiu! thank you 😁

**Comment by eradus** [comment]
> > > > > add
> > > > 
> > > > 
> > > > thanks ! 😁 It would be awesome for us if we could have a chat about the multichain section also but thanks for accepting our changes
> > > 
> > > 
> > > Please tell me your twitter acc, we can chat there if you like 🙏
> > 
> > 
> > Great! here it is: https://twitter.com/radu_enoiu! thank you 😁
> 
> yoo man, I just added you on twitter. Looks like you don't have DMs opened :)

pff, sorry bout, I forgot I disabled direct messages, too much spam 🙈  Fixed! 😁

**Pull request merged**
