### PR TITLE
Add GetBlock RPC Provider to the list

### PR DESCRIPTION
**Pull request by JoGetBlock**
Add GetBlock links to the list of providers

### CODE REVIEW

**Comment by arddluma** [comment]
Thanks for your submission, however as I have stated here in #multichain section (If you would like to be on the #Multichain list [Email Us](mailto:sponsor@multinodes.xyz) )
Also, please do not change the order of already submitted providers.
Thanks!

**Comment by JoGetBlock** [comment]
I'm sorry I missed that, yes I'd like GetBlock to be added to the
multichain list, as it is a provider that supports over 50 multiple
blockchains, you can keep the order as it is and list it at the end, it's
up to you, thank you kindly in advance!

**Comment by JoGetBlock** [comment]
Hello there, happy New Year! Are there any updates here?

**Comment by arddluma** [comment]
hey there @JoGetBlock ! Happy New Year!
I've just dropped an email, please check! thank you

**Comment by JoGetBlock** [comment]
Awesome, thanks! Though you've added GetBlock to some of the parts of the
list, that doesn't make any sense to me.
Also Why do we have to pay to be among the list each year when the other
projects are there for free?

Thank you for your answer in advance.

**Comment by arddluma** [comment]
This is the multichain section and those are the terms. If you are not interested then it is okay to me. Will close this PR.
Thank you!

**Comment by JoGetBlock** [comment]
What if we write an article about your multichain in our blog? Will that
work?

**Comment by arddluma** [comment]
> What if we write an article about your multichain in our blog? Will that work?
Appreciate your proposal, not interested thanks.

**Comment by JoGetBlock** [comment]
Hello Adrian, please do not close the issue, send us your invoice for the
offer.

**Comment by JoGetBlock** [comment]
Dear Adrian, I've managed to get the payment for the listing, but I need an
Invoice from you for that.

Thank you in advance.

**Pull request merged**
