### PR TITLE
Added DataHub under MultiChain providers and other networks

### PR DESCRIPTION
**Pull request by yash-sharma1**

### CODE REVIEW

**Comment by arddluma** [comment]
@yash-sharma1, please follow the order as everyone else.

**Comment by yash-sharma1** [comment]
> @yash-sharma1, please follow the order as everyone else.

Thanks for the heads-up @arddluma. Just updated the order

**Comment by arddluma** [comment]
@yash-sharma1 if you could please resolve conflicts? 🙏

**Comment by arddluma** [comment]
Hey @yash-sharma1,
Please resolve conflicts and remove entry from MultiChain section.
Thanks!

**Comment by arddluma** [comment]
Thanks for your contribution @yash-sharma1 , I just resolved conflicts and merged!

**Pull request merged**
