### PR TITLE
Add payload.de Ethereum RPC endpoint

### PR DESCRIPTION
**Pull request by cgebe**
Added the payload.de RPC endpoint to the Ethereum node list. Payload.de is our new block builder, we have started at the beginning of this year. The RPC endpoint supports the default `eth` & `net` APIs. Sent transactions are private and included when building blocks.

Docs: https://payload.de/docs/
Privacy Policy: https://payload.de/privacy/

### CODE REVIEW

**Comment by arddluma** [comment]
Hey @cgebe !
Thank you for your submission. Appreciate your effort to submit Payload to this list, unfortunately we cannot accept your submission because Payload is relatively new and supports only Ethereum network.
But, this doesn't mean that we will accept in the near future ;)

Best regards!

**Comment by cgebe** [comment]
Hey @arddluma
Thanks for the answer. I guess, we have misunderstood the listing, as we are only focusing on the provision of a public RPC endpoint for Ethereum. We are not the standard node provider (like Infura or Alchemy). We are primarily a builder for the Ethereum network which allows us to offer private transactions and bundle submission. We will not provide personal endpoints in the future, therefore i assume it is not a right fit for the current listing anyway! Have a nice one!

**Comment by arddluma** [comment]
> Hey @arddluma Thanks for the answer. I guess, we have misunderstood the listing, as we are only focusing on the provision of a public RPC endpoint for Ethereum. We are not the standard node provider (like Infura or Alchemy). We are primarily a builder for the Ethereum network which allows us to offer private transactions and bundle submission. We will not provide personal endpoints in the future, therefore i assume it is not a right fit for the current listing anyway! Have a nice one!

Thanks for explanation man! 
If that's the case, I will make an exception :) 
You can remove it from providers but leave public rpc as it is?! If you agree, I would be happy to merge this!
Thanks again.

**Comment by cgebe** [comment]
Hey @arddluma 
Thank you for clarification, that makes a lot more sense! If that's possible, that would be great. I have made the respective changes. 

Our interest is just to be listed in the README as we are currently increasing the functionality of our builder and want to get our name out there. We are active as german company for a longer time, but have recently started this service which hopefully grows in the long-term!

**Comment by arddluma** [comment]
> Hey @arddluma Thank you for clarification, that makes a lot more sense! If that's possible, that would be great. I have made the respective changes.
> 
> Our interest is just to be listed in the README as we are currently increasing the functionality of our builder and want to get our name out there. We are active as german company for a longer time, but have recently started this service which hopefully grows in the long-term!

Thanks for your contribution to the ecosystem!
Wish the best to Payload!
Best regards,
Ardd!

**Pull request merged**
