### PR TITLE
Add merkle RPC provider

### PR DESCRIPTION
**Pull request by Theo-**
Adding the merkle free RPC to the list of RPCs for Ethereum.

### CODE REVIEW

**Comment by Theo-** [comment]
hi @arddluma can we get this merged? let me know if anything is missing!

**Comment by arddluma** [comment]
> hi @arddluma can we get this merged? let me know if anything is missing!

Hello there,
Do you mind answering questions listed on our policy 
https://github.com/arddluma/awesome-list-rpc-nodes-providers/blob/main/.github/CONTRIBUTING.md
Thank you!

**Comment by Theo-** [comment]
Thanks for replying!

To answer your question:
- merkle hasn't been operating for a year, but everyone at merkle (including me) has been working in crypto for years
- we only offer free nodes

Thanks!

**Comment by arddluma** [comment]
> Thanks for replying!
> 
> To answer your question:
> 
> * merkle hasn't been operating for a year, but everyone at merkle (including me) has been working in crypto for years
> * we only offer free nodes
> 
> Thanks!

Thanks for your reply.
Appreciate what you guys are doing for the ecosystem! That's why I would be more than happy to accept your PR 🙏
Keep building ser!

**Comment by Theo-** [comment]
Thanks! Happy to contribute

**Pull request merged**
