### PR TITLE
Add NodeReal as a multi-chain service provider

### PR DESCRIPTION
**Pull request by huihzhao**

### CODE REVIEW

**Comment by arddluma** [comment]
Hey @huihzhao,
Sorry but we cannot accept anymore entries in #multichain section. So, could you please remove that ?
Thanks!

**Comment by huihzhao** [comment]
@arddluma Got it, thank you for your feedback.

**Comment by huihzhao** [comment]
@arddluma done, please review, thanks

**Comment by arddluma** [comment]
@huihzhao, please do not remove other providers to add yours. Could you pls fix that and let's merge it 🚀

**Review by arddluma — CHANGES_REQUESTED** [review]
as per comment above

**Comment by huihzhao** [comment]
@arddluma please review again, I only added the info, no other providers are removed. :)

**Comment by arddluma** [comment]
LGTM 🚀💯 Thanks for your contribution @huihzhao

**Pull request merged**
